class Peppol
  SCHEMEIDS=%w(AT:CID AT:GOV AT:KUR AT:VAT DK:CPR DK:CVR DK:P DK:SE DK:VANS DUNS ES:VAT EU:REID EU:VAT FI:OVT FR:SIRET GLN HU:VAT IBAN IS:KT IT:CF IT:FTI IT:SECETI IT:SIA IT:VAT NO:ORGNR NO:VAT SE:ORGNR)
end
